# coding: utf-8

"""
    Proxmox Backup Server API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AdminDatastoreCreatePruneDatastoreRequest(BaseModel):
    """
    AdminDatastoreCreatePruneDatastoreRequest
    """ # noqa: E501

    dry_run: Optional[StrictBool] = Field(default=False, description="Just show what prune would do, but do not delete anything.", alias="dry-run")

    keep_daily: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of daily backups to keep.", alias="keep-daily")

    keep_hourly: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of hourly backups to keep.", alias="keep-hourly")

    keep_last: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of backups to keep.", alias="keep-last")

    keep_monthly: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of monthly backups to keep.", alias="keep-monthly")

    keep_weekly: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of weekly backups to keep.", alias="keep-weekly")

    keep_yearly: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of yearly backups to keep.", alias="keep-yearly")

    max_depth: Optional[Annotated[int, Field(le=7, strict=True, ge=0)]] = Field(default=None, description="How many levels of namespaces should be operated on (0 == no recursion, empty == automatic full recursion, namespace depths reduce maximum allowed value)", alias="max-depth")

    ns: Optional[Annotated[str, Field(strict=True, max_length=256)]] = Field(default=None, description="Namespace.")

    __properties: ClassVar[List[str]] = ["dry-run", "keep-daily", "keep-hourly", "keep-last", "keep-monthly", "keep-weekly", "keep-yearly", "max-depth", "ns"]










    @field_validator('ns')
    def ns_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^(?:(?:(?:[A-Za-z0-9_][A-Za-z0-9._\-]*)/){0,7}(?:[A-Za-z0-9_][A-Za-z0-9._\-]*))?$", value):
            raise ValueError(r"must validate the regular expression /^(?:(?:(?:[A-Za-z0-9_][A-Za-z0-9._\-]*)/){0,7}(?:[A-Za-z0-9_][A-Za-z0-9._\-]*))?$/")
        return value



    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AdminDatastoreCreatePruneDatastoreRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AdminDatastoreCreatePruneDatastoreRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dry-run": obj.get("dry-run") if obj.get("dry-run") is not None else False,
            "keep-daily": obj.get("keep-daily"),
            "keep-hourly": obj.get("keep-hourly"),
            "keep-last": obj.get("keep-last"),
            "keep-monthly": obj.get("keep-monthly"),
            "keep-weekly": obj.get("keep-weekly"),
            "keep-yearly": obj.get("keep-yearly"),
            "max-depth": obj.get("max-depth"),
            "ns": obj.get("ns")
        })
        return _obj


