# coding: utf-8

"""
    Proxmox Backup Server API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from clientapi_pbs.models.admin_datastore_get_gc_response_data_cache_stats import AdminDatastoreGetGcResponseDataCacheStats
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AdminDatastoreGetGcResponseData(BaseModel):
    """
    AdminDatastoreGetGcResponseData
    """ # noqa: E501

    cache_stats: Optional[AdminDatastoreGetGcResponseDataCacheStats] = Field(default=None, alias="cache-stats")

    disk_bytes: Annotated[int, Field(strict=True, ge=0)] = Field(description="Bytes used on disk.", alias="disk-bytes")

    disk_chunks: Annotated[int, Field(strict=True, ge=0)] = Field(description="Chunks used on disk.", alias="disk-chunks")

    duration: Optional[StrictInt] = Field(default=None, description="Duration of last gc run")

    index_data_bytes: Annotated[int, Field(strict=True, ge=0)] = Field(description="Sum of bytes referred by index files.", alias="index-data-bytes")

    index_file_count: Annotated[int, Field(strict=True, ge=0)] = Field(description="Number of processed index files.", alias="index-file-count")

    last_run_endtime: Optional[StrictInt] = Field(default=None, description="Endtime of the last gc run", alias="last-run-endtime")

    last_run_state: Optional[StrictStr] = Field(default=None, description="State of the last gc run", alias="last-run-state")

    next_run: Optional[StrictInt] = Field(default=None, description="Time of the next gc run", alias="next-run")

    pending_bytes: Annotated[int, Field(strict=True, ge=0)] = Field(description="Sum of pending bytes (pending removal - kept for safety).", alias="pending-bytes")

    pending_chunks: Annotated[int, Field(strict=True, ge=0)] = Field(description="Number of pending chunks (pending removal - kept for safety).", alias="pending-chunks")

    removed_bad: Annotated[int, Field(strict=True, ge=0)] = Field(description="Number of chunks marked as .bad by verify that have been removed by GC.", alias="removed-bad")

    removed_bytes: Annotated[int, Field(strict=True, ge=0)] = Field(description="Sum of removed bytes.", alias="removed-bytes")

    removed_chunks: Annotated[int, Field(strict=True, ge=0)] = Field(description="Number of removed chunks.", alias="removed-chunks")

    schedule: Optional[StrictStr] = Field(default=None, description="Schedule of the gc job")

    still_bad: Annotated[int, Field(strict=True, ge=0)] = Field(description="Number of chunks still marked as .bad after garbage collection.", alias="still-bad")

    store: StrictStr = Field(description="Datastore")

    upid: Optional[Annotated[str, Field(min_length=36, strict=True)]] = Field(default=None, description="Unique Process/Task Identifier")

    __properties: ClassVar[List[str]] = ["cache-stats", "disk-bytes", "disk-chunks", "duration", "index-data-bytes", "index-file-count", "last-run-endtime", "last-run-state", "next-run", "pending-bytes", "pending-chunks", "removed-bad", "removed-bytes", "removed-chunks", "schedule", "still-bad", "store", "upid"]





















    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AdminDatastoreGetGcResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of cache_stats
        if self.cache_stats:
            _dict['cache-stats'] = self.cache_stats.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AdminDatastoreGetGcResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cache-stats": AdminDatastoreGetGcResponseDataCacheStats.from_dict(obj["cache-stats"]) if obj.get("cache-stats") is not None else None,
            "disk-bytes": obj.get("disk-bytes"),
            "disk-chunks": obj.get("disk-chunks"),
            "duration": obj.get("duration"),
            "index-data-bytes": obj.get("index-data-bytes"),
            "index-file-count": obj.get("index-file-count"),
            "last-run-endtime": obj.get("last-run-endtime"),
            "last-run-state": obj.get("last-run-state"),
            "next-run": obj.get("next-run"),
            "pending-bytes": obj.get("pending-bytes"),
            "pending-chunks": obj.get("pending-chunks"),
            "removed-bad": obj.get("removed-bad"),
            "removed-bytes": obj.get("removed-bytes"),
            "removed-chunks": obj.get("removed-chunks"),
            "schedule": obj.get("schedule"),
            "still-bad": obj.get("still-bad"),
            "store": obj.get("store"),
            "upid": obj.get("upid")
        })
        return _obj


