# coding: utf-8

"""
    Proxmox Backup Server API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from clientapi_pbs.models.pbs_config_datastore_inline_enum import PbsConfigDatastoreInlineEnum
from clientapi_pbs.models.pbs_maintenance_field import PbsMaintenanceField
from clientapi_pbs.models.pbs_notification_mode_enum import PbsNotificationModeEnum
from clientapi_pbs.models.pbs_notification_thresholds_field import PbsNotificationThresholdsField
from clientapi_pbs.models.pbs_notify_field import PbsNotifyField
from clientapi_pbs.models.pbs_tuning_field import PbsTuningField
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConfigDatastoreUpdateDatastoreRequest(BaseModel):
    """
    ConfigDatastoreUpdateDatastoreRequest
    """ # noqa: E501

    comment: Optional[Annotated[str, Field(strict=True, max_length=128)]] = Field(default=None, description="Comment.")

    counter_reset_schedule: Optional[StrictStr] = Field(default=None, description="Reset notification threshold related counters at specified schedule.", alias="counter-reset-schedule")

    delete: Optional[List[PbsConfigDatastoreInlineEnum]] = Field(default=None, description="List of properties to delete.")

    digest: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.")

    gc_on_unmount: Optional[StrictBool] = Field(default=None, description="Run garbage collection before unmounting a removable datastore.", alias="gc-on-unmount")

    gc_schedule: Optional[StrictStr] = Field(default=None, description="Run garbage collection job at specified schedule.", alias="gc-schedule")

    keep_daily: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of daily backups to keep.", alias="keep-daily")

    keep_hourly: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of hourly backups to keep.", alias="keep-hourly")

    keep_last: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of backups to keep.", alias="keep-last")

    keep_monthly: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of monthly backups to keep.", alias="keep-monthly")

    keep_weekly: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of weekly backups to keep.", alias="keep-weekly")

    keep_yearly: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of yearly backups to keep.", alias="keep-yearly")

    maintenance_mode: Optional[PbsMaintenanceField] = Field(default=None, description="Maintenance mode, type is either 'offline' or 'read-only', message should be enclosed in \"", alias="maintenance-mode")

    notification_mode: Optional[PbsNotificationModeEnum] = Field(default=None, description="Configure how notifications for this datastore should be sent. `legacy-sendmail` sends email notifications to the user configured in `notify-user` via the system's `sendmail` executable. `notification-system` emits matchable notification events to the notification system.", alias="notification-mode")

    notification_thresholds: Optional[PbsNotificationThresholdsField] = Field(default=None, description="Threshold values for notifications", alias="notification-thresholds")

    notify: Optional[PbsNotifyField] = Field(default=None, description="Datastore notification setting, enum can be one of 'always', 'never', or 'error'.")

    notify_user: Optional[Annotated[str, Field(min_length=3, strict=True, max_length=64)]] = Field(default=None, description="User ID", alias="notify-user")

    prune_schedule: Optional[StrictStr] = Field(default=None, description="Run prune job at specified schedule.", alias="prune-schedule")

    tuning: Optional[PbsTuningField] = Field(default=None, description="Datastore tuning options")

    verify_new: Optional[StrictBool] = Field(default=None, description="If enabled, all new backups will be verified right after completion.", alias="verify-new")

    __properties: ClassVar[List[str]] = ["comment", "counter-reset-schedule", "delete", "digest", "gc-on-unmount", "gc-schedule", "keep-daily", "keep-hourly", "keep-last", "keep-monthly", "keep-weekly", "keep-yearly", "maintenance-mode", "notification-mode", "notification-thresholds", "notify", "notify-user", "prune-schedule", "tuning", "verify-new"]


    @field_validator('comment')
    def comment_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[[:^cntrl:]]*$", value):
            raise ValueError(r"must validate the regular expression /^[[:^cntrl:]]*$/")
        return value




    @field_validator('digest')
    def digest_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[a-f0-9]{64}$", value):
            raise ValueError(r"must validate the regular expression /^[a-f0-9]{64}$/")
        return value














    @field_validator('notify_user')
    def notify_user_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^(?:[^\s:/[:cntrl:]]+)@(?:[A-Za-z0-9_][A-Za-z0-9._\-]*)$", value):
            raise ValueError(r"must validate the regular expression /^(?:[^\s:/[:cntrl:]]+)@(?:[A-Za-z0-9_][A-Za-z0-9._\-]*)$/")
        return value






    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConfigDatastoreUpdateDatastoreRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of maintenance_mode
        if self.maintenance_mode:
            _dict['maintenance-mode'] = self.maintenance_mode.to_dict()
        # override the default output from pydantic by calling `to_dict()` of notification_thresholds
        if self.notification_thresholds:
            _dict['notification-thresholds'] = self.notification_thresholds.to_dict()
        # override the default output from pydantic by calling `to_dict()` of notify
        if self.notify:
            _dict['notify'] = self.notify.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tuning
        if self.tuning:
            _dict['tuning'] = self.tuning.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConfigDatastoreUpdateDatastoreRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "comment": obj.get("comment"),
            "counter-reset-schedule": obj.get("counter-reset-schedule"),
            "delete": obj.get("delete"),
            "digest": obj.get("digest"),
            "gc-on-unmount": obj.get("gc-on-unmount"),
            "gc-schedule": obj.get("gc-schedule"),
            "keep-daily": obj.get("keep-daily"),
            "keep-hourly": obj.get("keep-hourly"),
            "keep-last": obj.get("keep-last"),
            "keep-monthly": obj.get("keep-monthly"),
            "keep-weekly": obj.get("keep-weekly"),
            "keep-yearly": obj.get("keep-yearly"),
            "maintenance-mode": PbsMaintenanceField.from_dict(obj["maintenance-mode"]) if obj.get("maintenance-mode") is not None else None,
            "notification-mode": obj.get("notification-mode"),
            "notification-thresholds": PbsNotificationThresholdsField.from_dict(obj["notification-thresholds"]) if obj.get("notification-thresholds") is not None else None,
            "notify": PbsNotifyField.from_dict(obj["notify"]) if obj.get("notify") is not None else None,
            "notify-user": obj.get("notify-user"),
            "prune-schedule": obj.get("prune-schedule"),
            "tuning": PbsTuningField.from_dict(obj["tuning"]) if obj.get("tuning") is not None else None,
            "verify-new": obj.get("verify-new")
        })
        return _obj


