# coding: utf-8

"""
    Proxmox Backup Server API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from clientapi_pbs.models.pbs_config_prune_inline_enum import PbsConfigPruneInlineEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConfigPruneUpdatePruneRequest(BaseModel):
    """
    ConfigPruneUpdatePruneRequest
    """ # noqa: E501

    comment: Optional[Annotated[str, Field(strict=True, max_length=128)]] = Field(default=None, description="Comment.")

    delete: Optional[List[PbsConfigPruneInlineEnum]] = Field(default=None, description="List of properties to delete.")

    digest: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.")

    disable: Optional[StrictBool] = Field(default=False, description="Disable this job.")

    keep_daily: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of daily backups to keep.", alias="keep-daily")

    keep_hourly: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of hourly backups to keep.", alias="keep-hourly")

    keep_last: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of backups to keep.", alias="keep-last")

    keep_monthly: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of monthly backups to keep.", alias="keep-monthly")

    keep_weekly: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of weekly backups to keep.", alias="keep-weekly")

    keep_yearly: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of yearly backups to keep.", alias="keep-yearly")

    max_depth: Optional[Annotated[int, Field(le=7, strict=True, ge=0)]] = Field(default=None, description="How many levels of namespaces should be operated on (0 == no recursion, empty == automatic full recursion, namespace depths reduce maximum allowed value)", alias="max-depth")

    ns: Optional[Annotated[str, Field(strict=True, max_length=256)]] = Field(default=None, description="Namespace.")

    schedule: Optional[StrictStr] = Field(default=None, description="Run prune job at specified schedule.")

    store: Optional[Annotated[str, Field(min_length=3, strict=True, max_length=32)]] = Field(default=None, description="Datastore name.")

    __properties: ClassVar[List[str]] = ["comment", "delete", "digest", "disable", "keep-daily", "keep-hourly", "keep-last", "keep-monthly", "keep-weekly", "keep-yearly", "max-depth", "ns", "schedule", "store"]


    @field_validator('comment')
    def comment_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[[:^cntrl:]]*$", value):
            raise ValueError(r"must validate the regular expression /^[[:^cntrl:]]*$/")
        return value



    @field_validator('digest')
    def digest_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[a-f0-9]{64}$", value):
            raise ValueError(r"must validate the regular expression /^[a-f0-9]{64}$/")
        return value










    @field_validator('ns')
    def ns_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^(?:(?:(?:[A-Za-z0-9_][A-Za-z0-9._\-]*)/){0,7}(?:[A-Za-z0-9_][A-Za-z0-9._\-]*))?$", value):
            raise ValueError(r"must validate the regular expression /^(?:(?:(?:[A-Za-z0-9_][A-Za-z0-9._\-]*)/){0,7}(?:[A-Za-z0-9_][A-Za-z0-9._\-]*))?$/")
        return value



    @field_validator('store')
    def store_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^(?:[A-Za-z0-9_][A-Za-z0-9._\-]*)$", value):
            raise ValueError(r"must validate the regular expression /^(?:[A-Za-z0-9_][A-Za-z0-9._\-]*)$/")
        return value



    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConfigPruneUpdatePruneRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            # `exclude_unset` keeps schema defaults out of the wire payload
            # when the user constructed the model directly (e.g.
            # `Req(vmid=100)` would otherwise pull in
            # `cores=1, cpulimit=0, …` from the spec defaults and PVE
            # rejects the request with 400 because it never set those).
            # `exclude_none` keeps None values out of the wire payload —
            # both for direct construction (None means "unset") and for
            # the from_dict path (where unspecified obj keys become
            # `obj.get("k") == None` but show up in `model_fields_set`).
            exclude_unset=True,
            exclude_none=True,
        )
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConfigPruneUpdatePruneRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "comment": obj.get("comment"),
            "delete": obj.get("delete"),
            "digest": obj.get("digest"),
            "disable": obj.get("disable") if obj.get("disable") is not None else False,
            "keep-daily": obj.get("keep-daily"),
            "keep-hourly": obj.get("keep-hourly"),
            "keep-last": obj.get("keep-last"),
            "keep-monthly": obj.get("keep-monthly"),
            "keep-weekly": obj.get("keep-weekly"),
            "keep-yearly": obj.get("keep-yearly"),
            "max-depth": obj.get("max-depth"),
            "ns": obj.get("ns"),
            "schedule": obj.get("schedule"),
            "store": obj.get("store")
        })
        return _obj


