# coding: utf-8

"""
    Proxmox Backup Server API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from clientapi_pbs.models.nodes_disks_get_list_response_data_inner_partitions_inner import NodesDisksGetListResponseDataInnerPartitionsInner
from clientapi_pbs.models.pbs_nodes_disks_disk_type_enum import PbsNodesDisksDiskTypeEnum
from clientapi_pbs.models.pbs_status_enum import PbsStatusEnum
from clientapi_pbs.models.pbs_usage_type_enum import PbsUsageTypeEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class NodesDisksGetListResponseDataInner(BaseModel):
    """
    NodesDisksGetListResponseDataInner
    """ # noqa: E501

    devpath: Optional[StrictStr] = Field(default=None, description="Linux device path (/dev/xxx)")

    disk_type: PbsNodesDisksDiskTypeEnum = Field(description="This is just a rough estimate for a \"type\" of disk.", alias="disk-type")

    gpt: StrictBool = Field(description="Set if disk contains a GPT partition table")

    model: Optional[StrictStr] = Field(default=None, description="Model")

    name: StrictStr = Field(description="Disk name (`/sys/block/<name>`)")

    partitions: Optional[List[NodesDisksGetListResponseDataInnerPartitionsInner]] = Field(default=None, description="Partitions on the device")

    rpm: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="RPM")

    serial: Optional[StrictStr] = Field(default=None, description="Serisal number")

    size: Annotated[int, Field(strict=True, ge=0)] = Field(description="Disk size")

    status: PbsStatusEnum = Field(description="SMART status")

    used: PbsUsageTypeEnum = Field(description="What a block device (disk) is used for.")

    vendor: Optional[StrictStr] = Field(default=None, description="Vendor")

    wearout: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Disk wearout")

    wwn: Optional[StrictStr] = Field(default=None, description="WWN")

    __properties: ClassVar[List[str]] = ["devpath", "disk-type", "gpt", "model", "name", "partitions", "rpm", "serial", "size", "status", "used", "vendor", "wearout", "wwn"]

















    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NodesDisksGetListResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            # `exclude_unset` keeps schema defaults out of the wire payload
            # when the user constructed the model directly (e.g.
            # `Req(vmid=100)` would otherwise pull in
            # `cores=1, cpulimit=0, …` from the spec defaults and PVE
            # rejects the request with 400 because it never set those).
            # `exclude_none` keeps None values out of the wire payload —
            # both for direct construction (None means "unset") and for
            # the from_dict path (where unspecified obj keys become
            # `obj.get("k") == None` but show up in `model_fields_set`).
            exclude_unset=True,
            exclude_none=True,
        )
        
        
        
        
        
        
        # override the default output from pydantic by calling `to_dict()` of each item in partitions (list)
        _items = []
        if self.partitions:
            for _item_partitions in self.partitions:
                if _item_partitions:
                    _items.append(_item_partitions.to_dict())
            _dict['partitions'] = _items
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NodesDisksGetListResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "devpath": obj.get("devpath"),
            "disk-type": obj.get("disk-type"),
            "gpt": obj.get("gpt"),
            "model": obj.get("model"),
            "name": obj.get("name"),
            "partitions": [NodesDisksGetListResponseDataInnerPartitionsInner.from_dict(_item) for _item in obj["partitions"]] if obj.get("partitions") is not None else None,
            "rpm": obj.get("rpm"),
            "serial": obj.get("serial"),
            "size": obj.get("size"),
            "status": obj.get("status"),
            "used": obj.get("used"),
            "vendor": obj.get("vendor"),
            "wearout": obj.get("wearout"),
            "wwn": obj.get("wwn")
        })
        return _obj


