# coding: utf-8

"""
    Proxmox Backup Server API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PbsProviderQuirksEnum(str, Enum):
    """
    PbsProviderQuirksEnum
    """

    """
    allowed enum values
    """
    SKIP_MINUS_IF_MINUS_NONE_MINUS_MATCH_MINUS_HEADER = 'skip-if-none-match-header'
    DELETE_MINUS_OBJECTS_MINUS_VIA_MINUS_DELETE_MINUS_OBJECT = 'delete-objects-via-delete-object'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PbsProviderQuirksEnum from a JSON string"""
        return cls(json.loads(json_str))


