# coding: utf-8

"""
    Proxmox Backup Server API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PbsConfigS3InlineEnum(str, Enum):
    """
    PbsConfigS3InlineEnum
    """

    """
    allowed enum values
    """
    PORT = 'port'
    REGION = 'region'
    FINGERPRINT = 'fingerprint'
    PATH_MINUS_STYLE = 'path-style'
    RATE_MINUS_IN = 'rate-in'
    BURST_MINUS_IN = 'burst-in'
    RATE_MINUS_OUT = 'rate-out'
    BURST_MINUS_OUT = 'burst-out'
    PROVIDER_MINUS_QUIRKS = 'provider-quirks'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PbsConfigS3InlineEnum from a JSON string"""
        return cls(json.loads(json_str))


