# coding: utf-8

"""
    Proxmox Backup Server API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PbsNodesSubscriptionStatusEnum(str, Enum):
    """
    PbsNodesSubscriptionStatusEnum
    """

    """
    allowed enum values
    """
    NEW = 'new'
    NOTFOUND = 'notfound'
    ACTIVE = 'active'
    INVALID = 'invalid'
    EXPIRED = 'expired'
    SUSPENDED = 'suspended'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PbsNodesSubscriptionStatusEnum from a JSON string"""
        return cls(json.loads(json_str))


