# coding: utf-8

"""
    Proxmox Backup Server API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PbsConfigVerifyInlineEnum(str, Enum):
    """
    PbsConfigVerifyInlineEnum
    """

    """
    allowed enum values
    """
    IGNORE_MINUS_VERIFIED = 'ignore-verified'
    COMMENT = 'comment'
    SCHEDULE = 'schedule'
    OUTDATED_MINUS_AFTER = 'outdated-after'
    NS = 'ns'
    MAX_MINUS_DEPTH = 'max-depth'
    READ_MINUS_THREADS = 'read-threads'
    VERIFY_MINUS_THREADS = 'verify-threads'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PbsConfigVerifyInlineEnum from a JSON string"""
        return cls(json.loads(json_str))


