# coding: utf-8

"""
    Proxmox Backup Server API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PbsDeleteEnum(str, Enum):
    """
    PbsDeleteEnum
    """

    """
    allowed enum values
    """
    SERVER2 = 'server2'
    PORT = 'port'
    COMMENT = 'comment'
    DEFAULT = 'default'
    VERIFY = 'verify'
    MODE = 'mode'
    BIND_MINUS_DN = 'bind-dn'
    PASSWORD = 'password'
    FILTER = 'filter'
    SYNC_MINUS_DEFAULTS_MINUS_OPTIONS = 'sync-defaults-options'
    SYNC_MINUS_ATTRIBUTES = 'sync-attributes'
    USER_MINUS_CLASSES = 'user-classes'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PbsDeleteEnum from a JSON string"""
        return cls(json.loads(json_str))


