# coding: utf-8

"""
    Proxmox Backup Server API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PbsTapeDriveDensityEnum(str, Enum):
    """
    PbsTapeDriveDensityEnum
    """

    """
    allowed enum values
    """
    UNKNOWN = 'Unknown'
    LTO1 = 'LTO1'
    LTO2 = 'LTO2'
    LTO3 = 'LTO3'
    LTO4 = 'LTO4'
    LTO5 = 'LTO5'
    LTO6 = 'LTO6'
    LTO7 = 'LTO7'
    LTO7M8 = 'LTO7M8'
    LTO8 = 'LTO8'
    LTO9 = 'LTO9'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PbsTapeDriveDensityEnum from a JSON string"""
        return cls(json.loads(json_str))


