# coding: utf-8

"""
    Proxmox Backup Server API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from clientapi_pbs.models.pbs_activity_enum import PbsActivityEnum
from clientapi_pbs.models.pbs_tape_drive_density_enum import PbsTapeDriveDensityEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TapeDriveGetStatusResponseData(BaseModel):
    """
    TapeDriveGetStatusResponseData
    """ # noqa: E501

    alert_flags: Optional[StrictStr] = Field(default=None, description="Tape Alert Flags", alias="alert-flags")

    block_number: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Current block number", alias="block-number")

    blocksize: Annotated[int, Field(le=4294967295, strict=True, ge=0)] = Field(description="Block size (0 is variable size)")

    buffer_mode: Annotated[int, Field(le=255, strict=True, ge=0)] = Field(description="Drive buffer mode", alias="buffer-mode")

    bytes_read: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Total Bytes Read in Medium Life", alias="bytes-read")

    bytes_written: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Total Bytes Written in Medium Life", alias="bytes-written")

    compression: StrictBool = Field(description="Compression enabled")

    density: Optional[PbsTapeDriveDensityEnum] = Field(default=None, description="The density of a tape medium, derived from the LTO version.")

    drive_activity: Optional[PbsActivityEnum] = Field(default=None, description="The DT Device Activity from DT Device Status LP page", alias="drive-activity")

    file_number: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Current file number", alias="file-number")

    manufactured: Optional[StrictInt] = Field(default=None, description="Medium Manufacture Date (epoch)")

    medium_passes: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Count of the total number of times the medium has passed over the head.", alias="medium-passes")

    medium_wearout: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Estimated tape wearout factor (assuming max. 16000 end-to-end passes)", alias="medium-wearout")

    product: StrictStr = Field(description="Product")

    revision: StrictStr = Field(description="Revision")

    vendor: StrictStr = Field(description="Vendor")

    volume_mounts: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Number of mounts for the current volume (i.e., Thread Count)", alias="volume-mounts")

    write_protect: Optional[StrictBool] = Field(default=None, description="Media is write protected", alias="write-protect")

    __properties: ClassVar[List[str]] = ["alert-flags", "block-number", "blocksize", "buffer-mode", "bytes-read", "bytes-written", "compression", "density", "drive-activity", "file-number", "manufactured", "medium-passes", "medium-wearout", "product", "revision", "vendor", "volume-mounts", "write-protect"]





















    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TapeDriveGetStatusResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            # `exclude_unset` keeps schema defaults out of the wire payload
            # when the user constructed the model directly (e.g.
            # `Req(vmid=100)` would otherwise pull in
            # `cores=1, cpulimit=0, …` from the spec defaults and PVE
            # rejects the request with 400 because it never set those).
            # `exclude_none` keeps None values out of the wire payload —
            # both for direct construction (None means "unset") and for
            # the from_dict path (where unspecified obj keys become
            # `obj.get("k") == None` but show up in `model_fields_set`).
            exclude_unset=True,
            exclude_none=True,
        )
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TapeDriveGetStatusResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alert-flags": obj.get("alert-flags"),
            "block-number": obj.get("block-number"),
            "blocksize": obj.get("blocksize"),
            "buffer-mode": obj.get("buffer-mode"),
            "bytes-read": obj.get("bytes-read"),
            "bytes-written": obj.get("bytes-written"),
            "compression": obj.get("compression"),
            "density": obj.get("density"),
            "drive-activity": obj.get("drive-activity"),
            "file-number": obj.get("file-number"),
            "manufactured": obj.get("manufactured"),
            "medium-passes": obj.get("medium-passes"),
            "medium-wearout": obj.get("medium-wearout"),
            "product": obj.get("product"),
            "revision": obj.get("revision"),
            "vendor": obj.get("vendor"),
            "volume-mounts": obj.get("volume-mounts"),
            "write-protect": obj.get("write-protect")
        })
        return _obj


