# coding: utf-8

"""
    Proxmox Backup Server API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TapeMediaCreateMoveRequest(BaseModel):
    """
    TapeMediaCreateMoveRequest
    """ # noqa: E501

    label_text: Optional[Annotated[str, Field(min_length=2, strict=True, max_length=32)]] = Field(default=None, description="Media Label/Barcode.", alias="label-text")

    uuid: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Media Uuid.")

    vault_name: Optional[Annotated[str, Field(min_length=3, strict=True, max_length=32)]] = Field(default=None, description="Vault name.", alias="vault-name")

    __properties: ClassVar[List[str]] = ["label-text", "uuid", "vault-name"]


    @field_validator('label_text')
    def label_text_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^(?:[A-Za-z0-9_][A-Za-z0-9._\-]*)$", value):
            raise ValueError(r"must validate the regular expression /^(?:[A-Za-z0-9_][A-Za-z0-9._\-]*)$/")
        return value


    @field_validator('uuid')
    def uuid_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$/")
        return value


    @field_validator('vault_name')
    def vault_name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^(?:[A-Za-z0-9_][A-Za-z0-9._\-]*)$", value):
            raise ValueError(r"must validate the regular expression /^(?:[A-Za-z0-9_][A-Za-z0-9._\-]*)$/")
        return value



    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TapeMediaCreateMoveRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TapeMediaCreateMoveRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "label-text": obj.get("label-text"),
            "uuid": obj.get("uuid"),
            "vault-name": obj.get("vault-name")
        })
        return _obj


