"""
    Proxmox Backup Server API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, field_validator
from typing import Optional
from typing_extensions import Annotated
from clientapi_pbs.models.backup_get_backup_response import BackupGetBackupResponse
from clientapi_pbs.models.pbs_backup_type_enum import PbsBackupTypeEnum

from clientapi_pbs.api_client import ApiClient, RequestSerialized
from clientapi_pbs.api_response import ApiResponse
from clientapi_pbs.rest import RESTResponseType


class BackupApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_backup(
        self,
        backup_id: Annotated[str, Field(strict=True, description="Backup ID.")],
        backup_time: Annotated[int, Field(strict=True, ge=1, description="Backup time (Unix epoch.)")],
        backup_type: Annotated[PbsBackupTypeEnum, Field(description="Backup type.")],
        store: Annotated[str, Field(min_length=3, strict=True, max_length=32, description="Datastore name.")],
        benchmark: Annotated[Optional[StrictBool], Field(description="Job is a benchmark (do not keep data).")] = None,
        debug: Annotated[Optional[StrictBool], Field(description="Enable verbose debug logging.")] = None,
        no_cache: Annotated[Optional[StrictBool], Field(description="Disable local datastore cache for network storages")] = None,
        ns: Annotated[Optional[Annotated[str, Field(strict=True, max_length=256)]], Field(description="Namespace.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> BackupGetBackupResponse:
        """Upgraded to backup protocol ('proxmox-backup-protocol-v1')

        Upgraded to backup protocol ('proxmox-backup-protocol-v1').  Permissions: Requires on /datastore/{store}[/{namespace}] DATASTORE_BACKUP and being the owner of the group

        :param backup_id: Backup ID. (required)
        :type backup_id: str
        :param backup_time: Backup time (Unix epoch.) (required)
        :type backup_time: int
        :param backup_type: Backup type. (required)
        :type backup_type: PbsBackupTypeEnum
        :param store: Datastore name. (required)
        :type store: str
        :param benchmark: Job is a benchmark (do not keep data).
        :type benchmark: bool
        :param debug: Enable verbose debug logging.
        :type debug: bool
        :param no_cache: Disable local datastore cache for network storages
        :type no_cache: bool
        :param ns: Namespace.
        :type ns: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_backup_serialize(
            backup_id=backup_id,
            backup_time=backup_time,
            backup_type=backup_type,
            store=store,
            benchmark=benchmark,
            debug=debug,
            no_cache=no_cache,
            ns=ns,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "BackupGetBackupResponse",
            '400': "PbsError",
            '401': "PbsError",
            '403': "PbsError",
            '404': "PbsError",
            '500': "PbsError",
            '501': "PbsError",
            '503': "PbsError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_backup_with_http_info(
        self,
        backup_id: Annotated[str, Field(strict=True, description="Backup ID.")],
        backup_time: Annotated[int, Field(strict=True, ge=1, description="Backup time (Unix epoch.)")],
        backup_type: Annotated[PbsBackupTypeEnum, Field(description="Backup type.")],
        store: Annotated[str, Field(min_length=3, strict=True, max_length=32, description="Datastore name.")],
        benchmark: Annotated[Optional[StrictBool], Field(description="Job is a benchmark (do not keep data).")] = None,
        debug: Annotated[Optional[StrictBool], Field(description="Enable verbose debug logging.")] = None,
        no_cache: Annotated[Optional[StrictBool], Field(description="Disable local datastore cache for network storages")] = None,
        ns: Annotated[Optional[Annotated[str, Field(strict=True, max_length=256)]], Field(description="Namespace.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[BackupGetBackupResponse]:
        """Upgraded to backup protocol ('proxmox-backup-protocol-v1')

        Upgraded to backup protocol ('proxmox-backup-protocol-v1').  Permissions: Requires on /datastore/{store}[/{namespace}] DATASTORE_BACKUP and being the owner of the group

        :param backup_id: Backup ID. (required)
        :type backup_id: str
        :param backup_time: Backup time (Unix epoch.) (required)
        :type backup_time: int
        :param backup_type: Backup type. (required)
        :type backup_type: PbsBackupTypeEnum
        :param store: Datastore name. (required)
        :type store: str
        :param benchmark: Job is a benchmark (do not keep data).
        :type benchmark: bool
        :param debug: Enable verbose debug logging.
        :type debug: bool
        :param no_cache: Disable local datastore cache for network storages
        :type no_cache: bool
        :param ns: Namespace.
        :type ns: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_backup_serialize(
            backup_id=backup_id,
            backup_time=backup_time,
            backup_type=backup_type,
            store=store,
            benchmark=benchmark,
            debug=debug,
            no_cache=no_cache,
            ns=ns,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "BackupGetBackupResponse",
            '400': "PbsError",
            '401': "PbsError",
            '403': "PbsError",
            '404': "PbsError",
            '500': "PbsError",
            '501': "PbsError",
            '503': "PbsError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_backup_without_preload_content(
        self,
        backup_id: Annotated[str, Field(strict=True, description="Backup ID.")],
        backup_time: Annotated[int, Field(strict=True, ge=1, description="Backup time (Unix epoch.)")],
        backup_type: Annotated[PbsBackupTypeEnum, Field(description="Backup type.")],
        store: Annotated[str, Field(min_length=3, strict=True, max_length=32, description="Datastore name.")],
        benchmark: Annotated[Optional[StrictBool], Field(description="Job is a benchmark (do not keep data).")] = None,
        debug: Annotated[Optional[StrictBool], Field(description="Enable verbose debug logging.")] = None,
        no_cache: Annotated[Optional[StrictBool], Field(description="Disable local datastore cache for network storages")] = None,
        ns: Annotated[Optional[Annotated[str, Field(strict=True, max_length=256)]], Field(description="Namespace.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Upgraded to backup protocol ('proxmox-backup-protocol-v1')

        Upgraded to backup protocol ('proxmox-backup-protocol-v1').  Permissions: Requires on /datastore/{store}[/{namespace}] DATASTORE_BACKUP and being the owner of the group

        :param backup_id: Backup ID. (required)
        :type backup_id: str
        :param backup_time: Backup time (Unix epoch.) (required)
        :type backup_time: int
        :param backup_type: Backup type. (required)
        :type backup_type: PbsBackupTypeEnum
        :param store: Datastore name. (required)
        :type store: str
        :param benchmark: Job is a benchmark (do not keep data).
        :type benchmark: bool
        :param debug: Enable verbose debug logging.
        :type debug: bool
        :param no_cache: Disable local datastore cache for network storages
        :type no_cache: bool
        :param ns: Namespace.
        :type ns: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_backup_serialize(
            backup_id=backup_id,
            backup_time=backup_time,
            backup_type=backup_type,
            store=store,
            benchmark=benchmark,
            debug=debug,
            no_cache=no_cache,
            ns=ns,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "BackupGetBackupResponse",
            '400': "PbsError",
            '401': "PbsError",
            '403': "PbsError",
            '404': "PbsError",
            '500': "PbsError",
            '501': "PbsError",
            '503': "PbsError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_backup_serialize(
        self,
        backup_id,
        backup_time,
        backup_type,
        store,
        benchmark,
        debug,
        no_cache,
        ns,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if backup_id is not None:
            
            _query_params.append(('backup-id', backup_id))
            
        if backup_time is not None:
            
            _query_params.append(('backup-time', backup_time))
            
        if backup_type is not None:
            
            _query_params.append(('backup-type', backup_type.value))
            
        if benchmark is not None:
            
            _query_params.append(('benchmark', benchmark))
            
        if debug is not None:
            
            _query_params.append(('debug', debug))
            
        if no_cache is not None:
            
            _query_params.append(('no-cache', no_cache))
            
        if ns is not None:
            
            _query_params.append(('ns', ns))
            
        if store is not None:
            
            _query_params.append(('store', store))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'PBSAuthCookie', 
            'PBSApiToken', 
            'CSRFPreventionToken'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/backup',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


